{% set name = "networkx-temporal" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/networkx_temporal-{{ version }}.tar.gz
  sha256: 29fcef4d770322177ccb9052d32aa232131b6ffab707a288c28d45d643333325

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - networkx >=2.1
    - pandas >=1.1.0

test:
  imports:
    - networkx_temporal
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Python package to build and manipulate dynamic NetworkX graphs.
  home: https://networkx-temporal.readthedocs.io/
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - mediocretech
